### ISSUE TITLE
Randomize the execution order of tests

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#181]
Randomize the execution order of tests by adding "--order rand" to .rspec.
 * rspec ./spec/features/contact_host_spec.rb 2 tests appear to need to be run top-to-bottom. Sometimes they both work and sometimes they both fail.

**Comment by jasnow** [comment]
May need to look the database_cleaner configuration too.

**Comment by jasnow** [comment]
Just got these 2 tests failed. (NOTE: Sometimes it works, sometimes it doesn't.)
 * rspec ./spec/features/contact_host_spec.rb:19
 * rspec ./spec/features/contact_host_spec.rb:34
```
  1) Visitor contacts host Visitor is notified when new host is available
     Failure/Error: expect(last_email_sent).to deliver_to(User.first.email)
       expected #<Mail::Message:81762370, Multipart: true, Headers: <Date: Fri, 15 Jan 2016 18:05:35 -0500>, <From: berniebnbinfo@gmail.com>, <To: facebook_user@fakemail.com>, <Message-ID: <56997b3f9e00a_51584b6d8ee661e2@jasnow-MXG061.mail>>, <Subject: Bernie BNB - New host near 11211!>, <Mime-Version: 1.0>, <Content-Type: multipart/alternative; boundary="--==_mimepart_56997b3f9c7d2_51584b6d8ee66093"; charset=UTF-8>, <Content-Transfer-Encoding: 7bit>> to deliver to ["jojo@yahoo.com"], but it delivered to ["facebook_user@fakemail.com"]
     # ./spec/features/contact_host_spec.rb:29:in `block (2 levels) in <top (required)>'

  2) Visitor contacts host Visitor finds and contacts a host
     Failure/Error: expect(last_email_sent).to deliver_to(User.first.email)
       expected #<Mail::Message:110954220, Multipart: true, Headers: <Date: Fri, 15 Jan 2016 18:05:36 -0500>, <From: berniebnbinfo@gmail.com>, <Reply-To: facebook_user@fakemail.com>, <To: gabriel@botsfordschaefer.org>, <Message-ID: <56997b40379f5_51584b6d8ee667b0@jasnow-MXG061.mail>>, <Subject: Bernie BNB - You've been contacted!>, <Mime-Version: 1.0>, <Content-Type: multipart/alternative; boundary="--==_mimepart_56997b403603f_51584b6d8ee66696"; charset=UTF-8>, <Content-Transfer-Encoding: 7bit>> to deliver to ["jojo@yahoo.com"], but it delivered to ["gabriel@botsfordschaefer.org"]
     # ./spec/features/contact_host_spec.rb:44:in `block (2 levels) in <top (required)>'
```

**Comment by jasnow** [comment]
See #239 - closing issue.
